### ISSUE TITLE
Use DbContext type from base Repository

### ISSUE THREAD

**Issue by nminaya** [scalex000/RepositoryPatternTemplate#1]
Why you would need to cast the DbContext to SofymaticContext?

https://github.com/scalex000/RepositoryPatternTemplate/blob/e8f2f5877abf4917f7cdc5e64f0d045c9215e5f4/Sofymatic.Repository/Sofymatic.Repository/Persistence/Repositories/CustomerRepository.cs#L17

**Comment by scalex000** [comment]
Because I have on SofymaticContext all dbset and in my BaseRepository only basic method.  This is the reason I create a property to typecast to SofymaticContext. it's I don't want to repeat on every method on my CustomerRepository.  Also, I'm applying encapsulation.

**Comment by nminaya** [comment]
@scalex000 you can use `.Set<T>() `method to get the `DbSet<T>` that you need.

**Comment by nminaya** [comment]
Also, the base class already has the DbSet
https://github.com/scalex000/RepositoryPatternTemplate/blob/e8f2f5877abf4917f7cdc5e64f0d045c9215e5f4/Sofymatic.Repository/Sofymatic.Repository/Persistence/Repositories/Repository.cs#L14

**Comment by scalex000** [comment]
> @scalex000 you can use `.Set<T>() `method to get the `DbSet<T>` that you need.

Yes, but, I don't want to be coupled to EF. on class SofymaticContext. I create a generic class for CRUD. 

> Why you would need to cast the DbContext to SofymaticContext?
> 
> https://github.com/scalex000/RepositoryPatternTemplate/blob/e8f2f5877abf4917f7cdc5e64f0d045c9215e5f4/Sofymatic.Repository/Sofymatic.Repository/Persistence/Repositories/CustomerRepository.cs#L17



> Because I have on SofymaticContext all dbset and in my BaseRepository only basic method. This is the reason I create a property to typecast to SofymaticContext. it's I don't want to repeat on every method on my CustomerRepository. Also, I'm applying encapsulation.

@nminaya I also practicing RepositoryPattern.

**Comment by scalex000** [comment]
The responsibility of CustomerRepository is to handle all queries of my Customer Domain Object.  It's not his responsibility to know about Repository.   To CustomerRepository doesn't care about who or where or what Repository does the implementation.

**Comment by nminaya** [comment]
> The responsibility of CustomerRepository is to handle all queries of my Customer Domain Object. It's not his responsibility to know about Repository. To CustomerRepository doesn't care about who or where or what Repository does the implementation.

Customer**Repository** is a **Repository**. It is his **responsability** to know about the Repository.

You said that the reason you cast DbContext to SofymaticContext is to get the DbSet that you want. But the base repository already has that DbSet instantiated.

https://github.com/scalex000/RepositoryPatternTemplate/blob/e8f2f5877abf4917f7cdc5e64f0d045c9215e5f4/Sofymatic.Repository/Sofymatic.Repository/Persistence/Repositories/Repository.cs#L19

In the case of CustomerRepository I guess that you want DbSet<Customer>. The base Repository already has that. 

So, IMHO I think this fileld should be protected
https://github.com/scalex000/RepositoryPatternTemplate/blob/e8f2f5877abf4917f7cdc5e64f0d045c9215e5f4/Sofymatic.Repository/Sofymatic.Repository/Persistence/Repositories/Repository.cs#L14

so derived classes would use that DbSet instead instantiate the same DbSet again.

**Comment by scalex000** [comment]
Yes, I can put protected, but this field it's an implementation detail.
