### ISSUE TITLE
Why I'm not use on Repository class <TEntity, TDBContext>?

### ISSUE THREAD

**Issue by scalex000** [scalex000/RepositoryPatternTemplate#3]
Well, It's simple I follow the principle a class only has one behavior.  So, I use to like this.
> public class Repository<TEntity> : IRepository<TEntity> where TEntity : class
The repository's only for doing all basic functionality.  "Single Responsibility"
@nminaya, @ralph819

**Comment by nminaya** [comment]
All DbContext inherit from DbContext. It is not necessary to have a generic type TDBContext to specify a DbContext type. It is enough that the repository is injected with a DbContext. So that you can inject any type of DbContext.

**Comment by scalex000** [comment]
Agree.
